import React from "react";
import QRCode from "qrcode.react";

function HuaqQR() {
  return (
    <div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol1"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol2"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol3"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol4"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol5"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol6"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol7"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol8"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol9"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol10"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol11"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol12"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol13"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol14"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol15"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol16"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol17"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol18"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol19"
          size={300}
          fgColor="#000"
        />
      </div>
      <div>
        <QRCode
          value="https://smigc.vercel.app/#/HuaqSymbol20"
          size={300}
          fgColor="#000"
        />
      </div>
    </div>
  );
}

export { HuaqQR };
